#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Requirements:
#         Accepts 4 parameters
#         The 1st parameter is the path to the file to be transferred
#         The 2nd parameter is the IP of the server we want to transfer the file to
#         The 3rd parameter is the username scp connects with
#         The 4th parameter is the path to the SSH private key that scp uses
#         Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
#         scp must transfer the file to the user home directory ~/
#         Strict host key checking must be disabled when using scp
# ssh key pair must be configured to use the created key pair
# File and directories can be created, moved and deleted.
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi