#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page.
# Requirements:
#       The redirection must be a “301 Moved Permanently”
#       You answer file should be a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
#       Using what you did with 1-install_nginx_web_server, write 2-setup_a_domain_name to automate the task of creating a domain name and to configure your Nginx server to redirect to the correct page.
#       Provide the domain name as answer file.
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

service nginx restart