#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page.
# Requirements:
#       The redirection must be a “301 Moved Permanently”
#       You answer file should be a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
#       Using what you did with 1-install_nginx_web_server, write 2-setup_a_domain_name to automate the task of creating a domain name and to configure your Nginx server to redirect to the correct page.
#       Provide the domain name as answer file.

sudo apt-get update
if [ ! -x /usr/bin/nginx ]; then 
     sudo apt-get -y install nginx
fi

if [ ! -d /var/www/nginx-html ]; then
     sudo mkdir -p /var/www/nginx-html
     touch /var/www/nginx-html/index.html
     echo "Hello World!" > /var/www/nginx-html/index.html
fi
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/nginx-html;
     index       index.html index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/default
service nginx restart
