#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page
# Requirements:
#       The page must return a 404 HTTP response code
#       The page must contain the string Ceci n'est pas une page

sudo apt-get update
if [ ! -x /usr/bin/nginx ]; then 
     sudo apt-get -y install nginx
fi

if [ ! -d /var/www/nginx-html ]; then
     sudo mkdir -p /var/www/nginx-html
     touch /var/www/nginx-html/index.html
     echo "Hello World!" > /var/www/nginx-html/index.html
fi

touch /var/www/nginx-html/404.html
echo "Ceci n'est pas une page" > /var/www/nginx-html/404.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/nginx-html;
     index       index.html index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404.html {
        root /var/www/nginx-html;
        internal;
    }
}
" > /etc/nginx/sites-available/default
service nginx restart
