#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page
# Requirements:
#       The page must return a 404 HTTP response code
#       The page must contain the string Ceci n'est pas une page
if [ ! -f /var/www/nginx-html/404.html ]; then
    touch /var/www/nginx-html/404.html
    echo "Ceci n'est pas une page" > /var/www/nginx-html/404.html
fi
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/nginx-html;
     index       index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
}
" > /etc/nginx/sites-available/default
service nginx restart