#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt-get update
if [ ! -x /usr/bin/nginx ]; then 
     sudo apt-get -y install nginx
fi

if [ ! -d /var/www/nginx-html ]; then
     sudo mkdir -p /var/www/nginx-html
fi

touch /var/www/nginx-html/index.html
echo "Hello World!" > /var/www/nginx-html/index.html

if [ ! -f /var/www/nginx-html/404.html ]; then
    touch /var/www/nginx-html/404.html
    echo -e "Ceci n'est pas une page" > /var/www/nginx-html/404.html
fi

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/nginx-html;
     index       index.html index.htm;
     add_header X-Served-By $HOSTNAME;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/nginx-html;
        internal;
    }
}
" > /etc/nginx/sites-available/default
service nginx restart