#!/usr/bin/env bash
# This script automates the fix of nginx not listening at port 80
 if [ ! -x /usr/sbin/nginx ];then
	 sudo apt install -y nginx
 fi
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
