#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal

file="/var/run/myscript.pid"
echo "$$" > "$file"

nope() {
	echo "I hate the kill command"
	sudo rm /var/run/myscript.pid
	exit 0
}

quit_now() {
	sudo rm /var/run/myscript.pid
	exit 0
}

no_love() {
	echo "Y U no love me?!"
}

trap 'nope' SIGTERM
trap 'no_love' SIGINT
trap 'quit_now' SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
