#!/usr/bin/env bash
# that displays Best School 10 times using while loop
# and then Hi on a new line after the 9th iteration.

num=1
while [ $num -le 10 ] ;
do
	echo "Best School"
	if [ $num -eq 9 ]
	then
		echo "Hi"
	fi
	num=$((num + 1))
done
