#!/usr/bin/env bash
# gives you information about the school file.
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)


all_file=$(find . -type f | wc -l)
count=0

for file in *
do
	if [ -e "$file" ] && [ "$file" == "school" ]
	then
		echo "school file exists"
		if [ -s "$file" ]
		then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		if [ -f "$file" ]
		then
			echo "school is a regular file"
		fi
		exit 0
	elif [ "$count" -eq "$all_file" ]
	then
		echo "school file does not exist"
		exit 0
	fi
	count=$((count + 1))
done
