#!/usr/bin/env bash
# displays all active IPv4 IPs on the machine it’s executed on.

interfaces=$(ifconfig -a | grep -oP '^\w+')
for interface in $interfaces; do
    ipv4=$(ifconfig "$interface" | grep -oP 'inet \K[\d.]+')
    if [ "$ipv4" ]; then
        echo "$ipv4"
    fi
done
